blank_issues_enabled: false
contact_links:
  - name: "Customer Requests"
    url: "https://external-portal-link.com"
    about: "Customer feature requests should be submitted in the dedicated external portal. Click the link to visit."
